services:
  ssdms-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ssdms_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "ssdms"
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    networks:
      ssdms-network:
        aliases:
          - ssdmsbase
    hostname: "ssdmsbase"
    container_name: ssdms-mysql

  ssdms-api:
    image: ssdms-api:1.0.0
    command: ["/wait-for-it.sh", "ssdms-mysql:3306", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: ssdmsbase
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    networks:
      - "ssdms-network"
    depends_on:
      - ssdms-mysql

  ssdms-proxy:
    build: ./nginx
    image: ssdms-proxy
    ports:
      - "80:80"
    networks:
      - "ssdms-network"
    depends_on:
      - ssdms-api
    container_name: ssdms-proxy

networks:
  ssdms-network:
    name: "ssdms-network"

volumes:
  ssdms_data:
    name: "ssdms_data"